<?php

declare(strict_types=1);

/**
 * Historical one-off converter retained only to document how the first
 * PostgreSQL bootstrap scripts were derived. SandAdmin releases ship the
 * reviewed PostgreSQL scripts directly and do not include MySQL bootstrap SQL.
 *
 * Usage:
 *   php tools/convert-sandadmin-sql.php
 */

final class SandAdminPostgresSqlConverter
{
    /** @var list<string> */
    private array $identityTables = [];

    public function convert(string $source): string
    {
        $sql = file_get_contents($source);
        if ($sql === false) {
            throw new RuntimeException("Unable to read {$source}");
        }

        $this->identityTables = [];
        $sql = preg_replace('/^SET\s+(?:NAMES|FOREIGN_KEY_CHECKS).*?;\s*$/mi', '', $sql) ?? $sql;
        // SandAdmin is an independent project. Its core persistence boundary
        // must not retain SaiAdmin's `sa_` table stem in generated PostgreSQL.
        $sql = str_replace(['sa_system_', 'sa_tool_'], ['sand_system_', 'sand_tool_'], $sql);
        // The upstream demo avatar is hosted remotely. Leave the field empty
        // in PostgreSQL bootstrap data so SandAdmin uses its built-in local
        // avatar and a local deployment has no external image dependency.
        $sql = str_replace("'https://image.saithink.top/sandadmin/avatar.jpg'", 'NULL', $sql);
        $sql = str_replace('\\"', '"', $sql);
        $sql = preg_replace_callback(
            '/DROP TABLE IF EXISTS `([^`]+)`;/',
            static fn (array $matches): string => sprintf('DROP TABLE IF EXISTS "%s" CASCADE;', $matches[1]),
            $sql,
        ) ?? $sql;
        $sql = preg_replace_callback(
            '/CREATE TABLE `([^`]+)`\s*\((.*?)\)\s*ENGINE\s*=?.*?;/si',
            fn (array $matches): string => $this->convertTable($matches[1], $matches[2]),
            $sql,
        ) ?? $sql;
        $sql = preg_replace('/INSERT INTO `([^`]+)` VALUES/i', 'INSERT INTO "$1" VALUES', $sql) ?? $sql;
        $sql = str_replace('`', '"', $sql);

        return trim($sql) . "\n\n" . $this->sequenceStatements() . "\n";
    }

    private function convertTable(string $table, string $body): string
    {
        $definitions = [];
        $indexes = [];

        foreach (preg_split('/\R/u', trim($body)) ?: [] as $line) {
            $line = trim($line);
            if ($line === '') {
                continue;
            }
            $line = rtrim($line, ',');

            if (str_starts_with($line, 'PRIMARY KEY')) {
                $definitions[] = $this->convertPrimaryKey($line);
                continue;
            }
            if (str_starts_with($line, 'UNIQUE INDEX') || str_starts_with($line, 'INDEX ')) {
                $indexes[] = $this->convertIndex($table, $line);
                continue;
            }

            $definitions[] = $this->convertColumn($table, $line);
        }

        return sprintf(
            "CREATE TABLE \"%s\" (\n  %s\n);\n%s",
            $table,
            implode(",\n  ", $definitions),
            implode("\n", $indexes),
        );
    }

    private function convertColumn(string $table, string $definition): string
    {
        if (!preg_match('/^`([^`]+)`\s+(.+)$/', $definition, $matches)) {
            throw new RuntimeException("Unsupported column definition in {$table}: {$definition}");
        }

        $column = $matches[1];
        $definition = $matches[2];
        $isIdentity = stripos($definition, 'AUTO_INCREMENT') !== false;

        $definition = preg_replace('/\s+COMMENT\s+\'(?:[^\'\\\\]|\\\\.)*\'/u', '', $definition) ?? $definition;
        $definition = preg_replace('/\s+UNSIGNED\b/i', '', $definition) ?? $definition;
        $definition = preg_replace('/\bAUTO_INCREMENT\b/i', 'GENERATED BY DEFAULT AS IDENTITY', $definition) ?? $definition;
        $definition = preg_replace('/\bBIGINT\(\d+\)/i', 'bigint', $definition) ?? $definition;
        $definition = preg_replace('/\bINT\(\d+\)/i', 'integer', $definition) ?? $definition;
        $definition = preg_replace('/\bSMALLINT\(\d+\)/i', 'smallint', $definition) ?? $definition;
        $definition = preg_replace('/\bTINYINT\(\d+\)/i', 'smallint', $definition) ?? $definition;
        $definition = preg_replace('/\bTIMESTAMP\(\d+\)/i', 'timestamp(0) without time zone', $definition) ?? $definition;
        $definition = preg_replace('/\bDATETIME(?:\(\d+\))?/i', 'timestamp(0) without time zone', $definition) ?? $definition;
        $definition = preg_replace('/\bLONGTEXT\b/i', 'text', $definition) ?? $definition;
        $definition = preg_replace('/\bMEDIUMTEXT\b/i', 'text', $definition) ?? $definition;
        $definition = preg_replace('/\bJSON\b/i', 'jsonb', $definition) ?? $definition;
        $definition = preg_replace('/\s+ON UPDATE CURRENT_TIMESTAMP(?:\(\d+\))?/i', '', $definition) ?? $definition;

        if ($isIdentity && $column === 'id') {
            $this->identityTables[] = $table;
        }

        return sprintf('"%s" %s', $column, trim($definition));
    }

    private function convertPrimaryKey(string $definition): string
    {
        $definition = preg_replace('/\s+USING\s+BTREE/i', '', $definition) ?? $definition;
        return str_replace('`', '"', $definition);
    }

    private function convertIndex(string $table, string $definition): string
    {
        if (!preg_match('/^(UNIQUE )?INDEX `([^`]+)`\((.+)\)(?: USING BTREE)?$/i', $definition, $matches)) {
            throw new RuntimeException("Unsupported index definition in {$table}: {$definition}");
        }

        $unique = $matches[1] !== '' ? 'UNIQUE ' : '';
        $name = sprintf('idx_%s_%s', $table, $matches[2]);
        $columns = preg_replace('/`([^`]+)`(?:\(\d+\))?/', '"$1"', $matches[3]) ?? $matches[3];

        return sprintf('CREATE %sINDEX "%s" ON "%s" (%s);', $unique, $name, $table, $columns);
    }

    private function sequenceStatements(): string
    {
        $tables = array_values(array_unique($this->identityTables));
        $statements = ['-- Keep identity sequences in sync with the explicit bootstrap IDs.'];
        foreach ($tables as $table) {
            $statements[] = sprintf(
                "SELECT setval(pg_get_serial_sequence('public.%s', 'id'), COALESCE((SELECT MAX(\"id\") FROM \"%s\"), 1), EXISTS (SELECT 1 FROM \"%s\"));",
                $table,
                $table,
                $table,
            );
        }

        return implode("\n", $statements);
    }
}

$directory = dirname(__DIR__) . '/plugin/sandadmin/db';
$converter = new SandAdminPostgresSqlConverter();
foreach (['sandadmin-6.0', 'sandadmin-pure'] as $name) {
    $target = $directory . '/' . $name . '.pgsql';
    file_put_contents($target, $converter->convert($directory . '/' . $name . '.sql'));
    fwrite(STDOUT, "Generated {$target}\n");
}
