-- ----------------------------
-- Table structure for sand_system_attachment
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_attachment" CASCADE;
CREATE TABLE "sand_system_attachment" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "category_id" integer NULL DEFAULT 0,
  "storage_mode" smallint NULL DEFAULT 1,
  "origin_name" varchar(255) NULL DEFAULT NULL,
  "object_name" varchar(50) NULL DEFAULT NULL,
  "hash" varchar(64) NULL DEFAULT NULL,
  "mime_type" varchar(255) NULL DEFAULT NULL,
  "storage_path" varchar(100) NULL DEFAULT NULL,
  "suffix" varchar(10) NULL DEFAULT NULL,
  "size_byte" bigint NULL DEFAULT NULL,
  "size_info" varchar(50) NULL DEFAULT NULL,
  "url" varchar(255) NULL DEFAULT NULL,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_attachment_hash" ON "sand_system_attachment" ("hash");
CREATE INDEX "idx_sand_system_attachment_idx_url" ON "sand_system_attachment" ("url");
CREATE INDEX "idx_sand_system_attachment_idx_create_time" ON "sand_system_attachment" ("create_time");
CREATE INDEX "idx_sand_system_attachment_idx_category_id" ON "sand_system_attachment" ("category_id");

-- ----------------------------
-- Records of sand_system_attachment
-- ----------------------------

-- ----------------------------
-- Table structure for sand_system_category
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_category" CASCADE;
CREATE TABLE "sand_system_category" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "parent_id" integer NOT NULL DEFAULT 0,
  "level" varchar(255) NULL DEFAULT NULL,
  "category_name" varchar(100) NOT NULL DEFAULT '',
  "sort" integer NOT NULL DEFAULT 0,
  "status" smallint NULL DEFAULT 1,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_category_pid" ON "sand_system_category" ("parent_id");
CREATE INDEX "idx_sand_system_category_sort" ON "sand_system_category" ("sort");

-- ----------------------------
-- Records of sand_system_category
-- ----------------------------
INSERT INTO "sand_system_category" VALUES (1, 0, '0,', '全部分类', 100, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_category" VALUES (2, 1, '0,1,', '图片分类', 100, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_category" VALUES (3, 1, '0,1,', '文件分类', 100, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_category" VALUES (4, 1, '0,1,', '系统图片', 100, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_category" VALUES (5, 1, '0,1,', '其他分类', 100, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);

-- ----------------------------
-- Table structure for sand_system_config
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_config" CASCADE;
CREATE TABLE "sand_system_config" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "group_id" integer NULL DEFAULT NULL,
  "key" varchar(32) NOT NULL,
  "value" text NULL,
  "name" varchar(255) NULL DEFAULT NULL,
  "input_type" varchar(32) NULL DEFAULT NULL,
  "config_select_data" varchar(500) NULL DEFAULT NULL,
  "sort" smallint NULL DEFAULT 0,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id", "key")
);
CREATE INDEX "idx_sand_system_config_group_id" ON "sand_system_config" ("group_id");

-- ----------------------------
-- Records of sand_system_config
-- ----------------------------
INSERT INTO "sand_system_config" VALUES (1, 1, 'site_copyright', 'Copyright © 2024 saithink', '版权信息', 'textarea', NULL, 96, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (2, 1, 'site_desc', '基于vue3 + webman 的极速开发框架', '网站描述', 'textarea', NULL, 97, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (3, 1, 'site_keywords', '后台管理系统', '网站关键字', 'input', NULL, 98, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (4, 1, 'site_name', 'SandAdmin', '网站名称', 'input', NULL, 99, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (5, 1, 'site_record_number', '9527', '网站备案号', 'input', NULL, 95, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (6, 2, 'upload_allow_file', 'txt,doc,docx,xls,xlsx,ppt,pptx,rar,zip,7z,gz,pdf,wps,md,jpg,png,jpeg,mp4,pem,crt', '文件类型', 'input', NULL, 0, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (7, 2, 'upload_allow_image', 'jpg,jpeg,png,gif,svg,bmp', '图片类型', 'input', NULL, 0, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (8, 2, 'upload_mode', '1', '上传模式', 'select', '[{"label":"本地上传","value":"1"},{"label":"阿里云OSS","value":"2"},{"label":"七牛云","value":"3"},{"label":"腾讯云COS","value":"4"},{"label":"亚马逊S3","value":"5"}]', 99, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (10, 2, 'upload_size', '52428800', '上传大小', 'input', NULL, 88, '单位Byte,1MB=1024*1024Byte', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (11, 2, 'local_root', 'public/storage/', '本地存储路径', 'input', NULL, 0, '本地存储文件路径', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (12, 2, 'local_domain', 'http://127.0.0.1:8787', '本地存储域名', 'input', NULL, 0, 'http://127.0.0.1:8787', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (13, 2, 'local_uri', '/storage/', '本地访问路径', 'input', NULL, 0, '访问是通过domain + uri', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (14, 2, 'qiniu_accessKey', '', '七牛key', 'input', NULL, 0, '七牛云存储secretId', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (15, 2, 'qiniu_secretKey', '', '七牛secret', 'input', NULL, 0, '七牛云存储secretKey', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (16, 2, 'qiniu_bucket', '', '七牛bucket', 'input', NULL, 0, '七牛云存储bucket', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (17, 2, 'qiniu_dirname', '', '七牛dirname', 'input', NULL, 0, '七牛云存储dirname', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (18, 2, 'qiniu_domain', '', '七牛domain', 'input', NULL, 0, '七牛云存储domain', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (19, 2, 'cos_secretId', '', '腾讯Id', 'input', NULL, 0, '腾讯云存储secretId', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (20, 2, 'cos_secretKey', '', '腾讯key', 'input', NULL, 0, '腾讯云secretKey', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (21, 2, 'cos_bucket', '', '腾讯bucket', 'input', NULL, 0, '腾讯云存储bucket', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (22, 2, 'cos_dirname', '', '腾讯dirname', 'input', NULL, 0, '腾讯云存储dirname', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (23, 2, 'cos_domain', '', '腾讯domain', 'input', NULL, 0, '腾讯云存储domain', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (24, 2, 'cos_region', '', '腾讯region', 'input', NULL, 0, '腾讯云存储region', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (25, 2, 'oss_accessKeyId', '', '阿里Id', 'input', NULL, 0, '阿里云存储accessKeyId', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (26, 2, 'oss_accessKeySecret', '', '阿里Secret', 'input', NULL, 0, '阿里云存储accessKeySecret', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (27, 2, 'oss_bucket', '', '阿里bucket', 'input', NULL, 0, '阿里云存储bucket', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (28, 2, 'oss_dirname', '', '阿里dirname', 'input', NULL, 0, '阿里云存储dirname', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (29, 2, 'oss_domain', '', '阿里domain', 'input', NULL, 0, '阿里云存储domain', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (30, 2, 'oss_endpoint', '', '阿里endpoint', 'input', NULL, 0, '阿里云存储endpoint', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (31, 3, 'Host', 'smtp.qq.com', 'SMTP服务器', 'input', '', 100, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (32, 3, 'Port', '465', 'SMTP端口', 'input', '', 100, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (33, 3, 'Username', '', 'SMTP用户名', 'input', '', 100, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (34, 3, 'Password', '', 'SMTP密码', 'input', '', 100, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (35, 3, 'SMTPSecure', 'ssl', 'SMTP验证方式', 'radio', '[\r\n    {"label":"ssl","value":"ssl"},\r\n    {"label":"tsl","value":"tsl"}\r\n]', 100, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (36, 3, 'From', '', '默认发件人', 'input', '', 100, '默认发件的邮箱地址', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (37, 3, 'FromName', '账户注册', '默认发件名称', 'input', '', 100, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (38, 3, 'CharSet', 'UTF-8', '编码', 'input', '', 100, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (39, 3, 'SMTPDebug', '0', '调试模式', 'radio', '[\r\n    {"label":"关闭","value":"0"},\r\n    {"label":"client","value":"1"},\r\n    {"label":"server","value":"2"}\r\n]', 100, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (40, 2, 's3_key', '', 'key', 'input', '', 0, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (41, 2, 's3_secret', '', 'secret', 'input', '', 0, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (42, 2, 's3_bucket', '', 'bucket', 'input', '', 0, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (43, 2, 's3_dirname', '', 'dirname', 'input', '', 0, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (44, 2, 's3_domain', '', 'domain', 'input', '', 0, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (45, 2, 's3_region', '', 'region', 'input', '', 0, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (46, 2, 's3_version', '', 'version', 'input', '', 0, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (47, 2, 's3_use_path_style_endpoint', '', 'path_style_endpoint', 'input', '', 0, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (48, 2, 's3_endpoint', '', 'endpoint', 'input', '', 0, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config" VALUES (49, 2, 's3_acl', '', 'acl', 'input', '', 0, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);

-- ----------------------------
-- Table structure for sand_system_config_group
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_config_group" CASCADE;
CREATE TABLE "sand_system_config_group" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(50) NULL DEFAULT NULL,
  "code" varchar(100) NULL DEFAULT NULL,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


-- ----------------------------
-- Records of sand_system_config_group
-- ----------------------------
INSERT INTO "sand_system_config_group" VALUES (1, '站点配置', 'site_config', '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config_group" VALUES (2, '上传配置', 'upload_config', NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_config_group" VALUES (3, '邮件服务', 'email_config', NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);

-- ----------------------------
-- Table structure for sand_system_dept
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_dept" CASCADE;
CREATE TABLE "sand_system_dept" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "parent_id" bigint NULL DEFAULT 0,
  "name" varchar(64) NOT NULL,
  "code" varchar(64) NULL DEFAULT NULL,
  "leader_id" bigint NULL DEFAULT NULL,
  "level" varchar(255) NULL DEFAULT '',
  "sort" integer NULL DEFAULT 0,
  "status" smallint NULL DEFAULT 1,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_dept_idx_parent_id" ON "sand_system_dept" ("parent_id");
CREATE INDEX "idx_sand_system_dept_idx_path" ON "sand_system_dept" ("level");

-- ----------------------------
-- Records of sand_system_dept
-- ----------------------------
INSERT INTO "sand_system_dept" VALUES (1, 0, '腾讯集团', 'GROUP', 1, '0,', 100, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);

-- ----------------------------
-- Table structure for sand_system_dict_data
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_dict_data" CASCADE;
CREATE TABLE "sand_system_dict_data" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "type_id" integer NULL DEFAULT NULL,
  "label" varchar(50) NULL DEFAULT NULL,
  "value" varchar(100) NULL DEFAULT NULL,
  "color" varchar(50) NULL DEFAULT NULL,
  "code" varchar(100) NULL DEFAULT NULL,
  "sort" smallint NULL DEFAULT 0,
  "status" smallint NULL DEFAULT 1,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_dict_data_type_id" ON "sand_system_dict_data" ("type_id");
CREATE INDEX "idx_sand_system_dict_data_idx_code" ON "sand_system_dict_data" ("code");

-- ----------------------------
-- Records of sand_system_dict_data
-- ----------------------------
INSERT INTO "sand_system_dict_data" VALUES (2, 2, '本地存储', '1', '#5d87ff', 'upload_mode', 99, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (3, 2, '阿里云OSS', '2', '#f9901f', 'upload_mode', 98, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (4, 2, '七牛云', '3', '#00ced1', 'upload_mode', 97, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (5, 2, '腾讯云COS', '4', '#1d84ff', 'upload_mode', 96, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (6, 2, '亚马逊S3', '5', '#ff80c8', 'upload_mode', 95, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (7, 3, '正常', '1', '#13deb9', 'data_status', 0, 1, '1为正常', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (8, 3, '停用', '2', '#ff4d4f', 'data_status', 0, 1, '2为停用', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (9, 4, '统计页面', 'statistics', '#00ced1', 'dashboard', 100, 1, '管理员用', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (10, 4, '工作台', 'work', '#ff8c00', 'dashboard', 50, 1, '员工使用', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (11, 5, '男', '1', '#5d87ff', 'gender', 0, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (12, 5, '女', '2', '#ff4500', 'gender', 0, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (13, 5, '未知', '3', '#b48df3', 'gender', 0, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (16, 12, '图片', 'image', '#60c041', 'attachment_type', 10, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (17, 12, '文档', 'text', '#1d84ff', 'attachment_type', 9, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (18, 12, '音频', 'audio', '#00ced1', 'attachment_type', 8, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (19, 12, '视频', 'video', '#ff4500', 'attachment_type', 7, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (20, 12, '应用程序', 'application', '#ff8c00', 'attachment_type', 6, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (21, 13, '目录', '1', '#909399', 'menu_type', 100, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (22, 13, '菜单', '2', '#1e90ff', 'menu_type', 100, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (23, 13, '按钮', '3', '#ff4500', 'menu_type', 100, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (24, 13, '外链', '4', '#00ced1', 'menu_type', 100, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (25, 14, '是', '1', '#60c041', 'yes_or_no', 100, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (26, 14, '否', '2', '#ff4500', 'yes_or_no', 100, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (47, 20, 'URL任务GET', '1', '#5d87ff', 'crontab_task_type', 100, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (48, 20, 'URL任务POST', '2', '#00ced1', 'crontab_task_type', 100, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_data" VALUES (49, 20, '类任务', '3', '#ff8c00', 'crontab_task_type', 100, 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);

-- ----------------------------
-- Table structure for sand_system_dict_type
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_dict_type" CASCADE;
CREATE TABLE "sand_system_dict_type" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(50) NULL DEFAULT NULL,
  "code" varchar(100) NULL DEFAULT NULL,
  "status" smallint NULL DEFAULT 1,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_dict_type_idx_code" ON "sand_system_dict_type" ("code");
CREATE INDEX "idx_sand_system_dict_type_idx_name" ON "sand_system_dict_type" ("name");

-- ----------------------------
-- Records of sand_system_dict_type
-- ----------------------------
INSERT INTO "sand_system_dict_type" VALUES (2, '存储模式', 'upload_mode', 1, '上传文件存储模式', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_type" VALUES (3, '数据状态', 'data_status', 1, '通用数据状态', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_type" VALUES (4, '后台首页', 'dashboard', 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_type" VALUES (5, '性别', 'gender', 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_type" VALUES (12, '附件类型', 'attachment_type', 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_type" VALUES (13, '菜单类型', 'menu_type', 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_type" VALUES (14, '是否', 'yes_or_no', 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_dict_type" VALUES (20, '定时任务类型', 'crontab_task_type', 1, '', 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);

-- ----------------------------
-- Table structure for sand_system_login_log
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_login_log" CASCADE;
CREATE TABLE "sand_system_login_log" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" varchar(20) NULL DEFAULT NULL,
  "ip" varchar(45) NULL DEFAULT NULL,
  "ip_location" varchar(255) NULL DEFAULT NULL,
  "os" varchar(50) NULL DEFAULT NULL,
  "browser" varchar(50) NULL DEFAULT NULL,
  "status" smallint NULL DEFAULT 1,
  "message" varchar(50) NULL DEFAULT NULL,
  "login_time" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_login_log_username" ON "sand_system_login_log" ("username");
CREATE INDEX "idx_sand_system_login_log_idx_create_time" ON "sand_system_login_log" ("create_time");
CREATE INDEX "idx_sand_system_login_log_idx_login_time" ON "sand_system_login_log" ("login_time");

-- ----------------------------
-- Records of sand_system_login_log
-- ----------------------------

-- ----------------------------
-- Table structure for sand_system_mail
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_mail" CASCADE;
CREATE TABLE "sand_system_mail" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "gateway" varchar(50) NULL DEFAULT NULL,
  "from" varchar(50) NULL DEFAULT NULL,
  "email" varchar(50) NULL DEFAULT NULL,
  "code" varchar(20) NULL DEFAULT NULL,
  "content" varchar(500) NULL DEFAULT NULL,
  "status" varchar(20) NULL DEFAULT NULL,
  "response" varchar(500) NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_mail_idx_create_time" ON "sand_system_mail" ("create_time");

-- ----------------------------
-- Records of sand_system_mail
-- ----------------------------

-- ----------------------------
-- Table structure for sand_system_menu
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_menu" CASCADE;
CREATE TABLE "sand_system_menu" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "parent_id" bigint NULL DEFAULT 0,
  "name" varchar(64) NOT NULL,
  "code" varchar(64) NULL DEFAULT NULL,
  "slug" varchar(100) NULL DEFAULT NULL,
  "type" smallint NOT NULL DEFAULT 1,
  "path" varchar(255) NULL DEFAULT NULL,
  "component" varchar(255) NULL DEFAULT NULL,
  "method" varchar(10) NULL DEFAULT NULL,
  "icon" varchar(64) NULL DEFAULT NULL,
  "sort" integer NULL DEFAULT 100,
  "link_url" varchar(255) NULL DEFAULT NULL,
  "is_iframe" smallint NULL DEFAULT 2,
  "is_keep_alive" smallint NULL DEFAULT 2,
  "is_hidden" smallint NULL DEFAULT 2,
  "is_fixed_tab" smallint NULL DEFAULT 2,
  "is_full_page" smallint NULL DEFAULT 2,
  "generate_id" integer NULL DEFAULT 0,
  "generate_key" varchar(255) NULL DEFAULT NULL,
  "status" smallint NULL DEFAULT 1,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_menu_idx_parent_id" ON "sand_system_menu" ("parent_id");
CREATE INDEX "idx_sand_system_menu_idx_slug" ON "sand_system_menu" ("slug");

-- ----------------------------
-- Records of sand_system_menu
-- ----------------------------
INSERT INTO "sand_system_menu" VALUES (1, 0, '仪表盘', 'Dashboard', NULL, 1, '/dashboard', NULL, NULL, 'ri:pie-chart-line', 100, NULL, 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (2, 1, '工作台', 'Console', NULL, 2, 'console', '/dashboard/console', NULL, 'ri:home-smile-2-line', 100, NULL, 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (3, 0, '系统管理', 'System', NULL, 1, '/system', NULL, NULL, 'ri:user-3-line', 100, NULL, 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (4, 3, '用户管理', 'User', NULL, 2, 'user', '/system/user', NULL, 'ri:user-line', 100, NULL, 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (5, 3, '部门管理', 'Dept', NULL, 2, 'dept', '/system/dept', NULL, 'ri:node-tree', 100, NULL, 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (6, 3, '角色管理', 'Role', NULL, 2, 'role', '/system/role', NULL, 'ri:admin-line', 100, NULL, 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (7, 3, '岗位管理', 'Post', '', 2, 'post', '/system/post', NULL, 'ri:signpost-line', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (8, 3, '菜单管理', 'Menu', NULL, 2, 'menu', '/system/menu', NULL, 'ri:menu-line', 100, NULL, 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (10, 0, '运维管理', 'Safeguard', NULL, 1, '/safeguard', '', NULL, 'ri:shield-check-line', 100, NULL, 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (11, 10, '缓存管理', 'Cache', '', 2, 'cache', '/safeguard/cache', NULL, 'ri:keyboard-box-line', 80, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (12, 10, '数据字典', 'Dict', NULL, 2, 'dict', '/safeguard/dict', NULL, 'ri:database-2-line', 100, NULL, 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (13, 10, '附件管理', 'Attachment', '', 2, 'attachment', '/safeguard/attachment', NULL, 'ri:file-cloud-line', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (14, 10, '数据表维护', 'Database', '', 2, 'database', '/safeguard/database', NULL, 'ri:database-line', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (15, 10, '登录日志', 'LoginLog', '', 2, 'login-log', '/safeguard/login-log', NULL, 'ri:login-circle-line', 50, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (16, 10, '操作日志', 'OperLog', '', 2, 'oper-log', '/safeguard/oper-log', NULL, 'ri:shield-keyhole-line', 50, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (17, 10, '邮件日志', 'EmailLog', '', 2, 'email-log', '/safeguard/email-log', NULL, 'ri:mail-line', 50, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (18, 3, '系统设置', 'Config', NULL, 2, 'config', '/system/config', NULL, 'ri:settings-4-line', 100, NULL, 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (19, 0, '项目文档', 'Document', '', 4, '', '', NULL, 'ri:file-copy-2-fill', 90, 'https://github.com/supdger/sandadmin/tree/main/docs', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (20, 4, '数据列表', '', 'core:user:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (21, 1, '个人中心', 'UserCenter', '', 2, 'user-center', '/dashboard/user-center/index', NULL, 'ri:user-2-line', 100, '', 2, 2, 1, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (22, 4, '添加', '', 'core:user:save', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (23, 4, '修改', '', 'core:user:update', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (24, 4, '读取', '', 'core:user:read', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (25, 4, '删除', '', 'core:user:destroy', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (26, 4, '重置密码', '', 'core:user:password', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (27, 4, '清理缓存', '', 'core:user:cache', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (28, 4, '设置工作台', '', 'core:user:home', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (29, 5, '数据列表', '', 'core:dept:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (30, 5, '添加', '', 'core:dept:save', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (31, 5, '修改', '', 'core:dept:update', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (32, 5, '读取', '', 'core:dept:read', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (33, 5, '删除', '', 'core:dept:destroy', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (34, 6, '添加', '', 'core:role:save', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (35, 6, '数据列表', '', 'core:role:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (36, 6, '修改', '', 'core:role:update', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (37, 6, '读取', '', 'core:role:read', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (38, 6, '删除', '', 'core:role:destroy', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (39, 6, '菜单权限', '', 'core:role:menu', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (41, 7, '数据列表', '', 'core:post:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (42, 7, '添加', '', 'core:post:save', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (43, 7, '修改', '', 'core:post:update', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (44, 7, '读取', '', 'core:post:read', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (45, 7, '删除', '', 'core:post:destroy', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (46, 7, '导入', '', 'core:post:import', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (47, 7, '导出', '', 'core:post:export', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (48, 8, '数据列表', '', 'core:menu:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (49, 8, '读取', '', 'core:menu:read', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (50, 8, '添加', '', 'core:menu:save', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (51, 8, '修改', '', 'core:menu:update', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (52, 8, '删除', '', 'core:menu:destroy', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (53, 18, '数据列表', '', 'core:config:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (54, 18, '管理', '', 'core:config:edit', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (55, 18, '修改', '', 'core:config:update', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (56, 12, '数据列表', '', 'core:dict:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (57, 12, '管理', '', 'core:dict:edit', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (58, 13, '数据列表', '', 'core:attachment:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (59, 13, '管理', '', 'core:attachment:edit', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (60, 14, '数据表列表', '', 'core:database:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (61, 14, '数据表维护', '', 'core:database:edit', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (62, 14, '回收站数据', '', 'core:recycle:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (63, 14, '回收站管理', '', 'core:recycle:edit', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (64, 15, '数据列表', '', 'core:logs:login', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (65, 15, '删除', '', 'core:logs:deleteLogin', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (66, 16, '数据列表', '', 'core:logs:Oper', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (67, 16, '删除', '', 'core:logs:deleteOper', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (68, 17, '数据列表', '', 'core:email:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (69, 17, '删除', '', 'core:email:destroy', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (70, 10, '服务监控', 'Server', '', 2, 'server', '/safeguard/server', NULL, 'ri:server-line', 90, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (71, 70, '数据列表', '', 'core:server:monitor', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (72, 11, '数据列表', '', 'core:server:cache', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (73, 11, '缓存清理', '', 'core:server:clear', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (74, 2, '登录数据统计', '', 'core:console:list', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (75, 0, '附加权限', 'Permission', '', 1, 'permission', '', NULL, 'ri:apps-2-ai-line', 100, '', 2, 2, 1, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (76, 75, '上传图片', '', 'core:system:uploadImage', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (77, 75, '上传文件', '', 'core:system:uploadFile', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (78, 75, '附件列表', '', 'core:system:resource', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (79, 75, '用户列表', '', 'core:system:user', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (80, 0, '工具', 'Tool', '', 1, '/tool', '', NULL, 'ri:tools-line', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (81, 80, '代码生成', 'Code', '', 2, 'code', '/tool/code', NULL, 'ri:code-s-slash-line', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (82, 80, '定时任务', 'Crontab', '', 2, 'crontab', '/tool/crontab', NULL, 'ri:time-line', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (83, 82, '数据列表', '', 'tool:crontab:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (84, 82, '管理', '', 'tool:crontab:edit', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (85, 82, '运行任务', '', 'tool:crontab:run', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (86, 81, '数据列表', '', 'tool:code:index', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (87, 81, '管理', '', 'tool:code:edit', 3, '', '', NULL, '', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);
INSERT INTO "sand_system_menu" VALUES (88, 0, '插件市场', 'Plugin', '', 2, '/plugin', '/plugin/sandpackage/install/index', NULL, 'ri:apps-2-ai-line', 100, '', 2, 2, 2, 2, 2, 0, NULL, 1, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);

-- ----------------------------
-- Table structure for sand_system_oper_log
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_oper_log" CASCADE;
CREATE TABLE "sand_system_oper_log" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" varchar(20) NULL DEFAULT NULL,
  "app" varchar(50) NULL DEFAULT NULL,
  "method" varchar(20) NULL DEFAULT NULL,
  "router" varchar(500) NULL DEFAULT NULL,
  "service_name" varchar(30) NULL DEFAULT NULL,
  "ip" varchar(45) NULL DEFAULT NULL,
  "ip_location" varchar(255) NULL DEFAULT NULL,
  "request_data" text NULL,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_oper_log_username" ON "sand_system_oper_log" ("username");
CREATE INDEX "idx_sand_system_oper_log_idx_create_time" ON "sand_system_oper_log" ("create_time");

-- ----------------------------
-- Records of sand_system_oper_log
-- ----------------------------

-- ----------------------------
-- Table structure for sand_system_post
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_post" CASCADE;
CREATE TABLE "sand_system_post" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(50) NULL DEFAULT NULL,
  "code" varchar(100) NULL DEFAULT NULL,
  "sort" smallint NULL DEFAULT 0,
  "status" smallint NULL DEFAULT 1,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


-- ----------------------------
-- Table structure for sand_system_role
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_role" CASCADE;
CREATE TABLE "sand_system_role" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(64) NOT NULL,
  "code" varchar(64) NOT NULL,
  "level" integer NULL DEFAULT 1,
  "data_scope" smallint NULL DEFAULT 1,
  "remark" varchar(255) NULL DEFAULT NULL,
  "sort" integer NULL DEFAULT 100,
  "status" smallint NULL DEFAULT 1,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "idx_sand_system_role_uk_slug" ON "sand_system_role" ("code");

-- ----------------------------
-- Records of sand_system_role
-- ----------------------------
INSERT INTO "sand_system_role" VALUES (1, '超级管理员', 'super_admin', 100, 1, '系统维护者，拥有所有权限', 100, 1, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);

-- ----------------------------
-- Table structure for sand_system_role_dept
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_role_dept" CASCADE;
CREATE TABLE "sand_system_role_dept" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role_id" bigint NOT NULL,
  "dept_id" bigint NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_role_dept_idx_role_id" ON "sand_system_role_dept" ("role_id");
CREATE INDEX "idx_sand_system_role_dept_idx_dept_id" ON "sand_system_role_dept" ("dept_id");

-- ----------------------------
-- Records of sand_system_role_dept
-- ----------------------------

-- ----------------------------
-- Table structure for sand_system_role_menu
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_role_menu" CASCADE;
CREATE TABLE "sand_system_role_menu" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role_id" bigint NOT NULL,
  "menu_id" bigint NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_role_menu_idx_menu_id" ON "sand_system_role_menu" ("menu_id");
CREATE INDEX "idx_sand_system_role_menu_idx_role_id" ON "sand_system_role_menu" ("role_id");

-- ----------------------------
-- Records of sand_system_role_menu
-- ----------------------------

-- ----------------------------
-- Table structure for sand_system_user
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_user" CASCADE;
CREATE TABLE "sand_system_user" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" varchar(64) NOT NULL,
  "password" varchar(255) NOT NULL,
  "realname" varchar(64) NULL DEFAULT NULL,
  "gender" varchar(10) NULL DEFAULT NULL,
  "avatar" varchar(255) NULL DEFAULT NULL,
  "email" varchar(128) NULL DEFAULT NULL,
  "phone" varchar(20) NULL DEFAULT NULL,
  "signed" varchar(255) NULL DEFAULT NULL,
  "dashboard" varchar(255) NULL DEFAULT 'work',
  "dept_id" bigint NULL DEFAULT NULL,
  "is_super" smallint NULL DEFAULT 0,
  "status" smallint NULL DEFAULT 1,
  "remark" varchar(255) NULL DEFAULT NULL,
  "login_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "login_ip" varchar(45) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "idx_sand_system_user_uk_username" ON "sand_system_user" ("username");
CREATE INDEX "idx_sand_system_user_idx_dept_id" ON "sand_system_user" ("dept_id");

-- ----------------------------
-- Records of sand_system_user
-- ----------------------------
INSERT INTO "sand_system_user" VALUES (1, 'admin', '$2y$10$wnixh48uDnaW/6D9EygDd.OHJK0vQY/4nHaTjMKBCVDBP2NiTatqS', '祭道之上', '2', NULL, 'sandadmin@admin.com', '15888888888', 'SandAdmin是兼具设计美学与高效开发的后台系统!', 'statistics', 1, 1, 1, NULL, NULL, NULL, 1, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL);

-- ----------------------------
-- Table structure for sand_system_user_post
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_user_post" CASCADE;
CREATE TABLE "sand_system_user_post" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL,
  "post_id" bigint NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_user_post_idx_user_id" ON "sand_system_user_post" ("user_id");
CREATE INDEX "idx_sand_system_user_post_idx_post_id" ON "sand_system_user_post" ("post_id");

-- ----------------------------
-- Records of sand_system_user_post
-- ----------------------------

-- ----------------------------
-- Table structure for sand_system_user_role
-- ----------------------------
DROP TABLE IF EXISTS "sand_system_user_role" CASCADE;
CREATE TABLE "sand_system_user_role" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "idx_sand_system_user_role_idx_role_id" ON "sand_system_user_role" ("role_id");
CREATE INDEX "idx_sand_system_user_role_idx_user_id" ON "sand_system_user_role" ("user_id");

-- ----------------------------
-- Records of sand_system_user_role
-- ----------------------------
INSERT INTO "sand_system_user_role" VALUES (1, 1, 1);

-- ----------------------------
-- Table structure for sand_tool_crontab
-- ----------------------------
DROP TABLE IF EXISTS "sand_tool_crontab" CASCADE;
CREATE TABLE "sand_tool_crontab" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(100) NULL DEFAULT NULL,
  "type" smallint NULL DEFAULT 4,
  "target" varchar(500) NULL DEFAULT NULL,
  "parameter" varchar(1000) NULL DEFAULT NULL,
  "task_style" smallint NULL DEFAULT NULL,
  "rule" varchar(32) NULL DEFAULT NULL,
  "singleton" smallint NULL DEFAULT 1,
  "status" smallint NULL DEFAULT 1,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


-- ----------------------------
-- Table structure for sand_tool_crontab_log
-- ----------------------------
DROP TABLE IF EXISTS "sand_tool_crontab_log" CASCADE;
CREATE TABLE "sand_tool_crontab_log" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "crontab_id" integer NULL DEFAULT NULL,
  "name" varchar(255) NULL DEFAULT NULL,
  "target" varchar(500) NULL DEFAULT NULL,
  "parameter" varchar(1000) NULL DEFAULT NULL,
  "exception_info" varchar(2000) NULL DEFAULT NULL,
  "status" smallint NULL DEFAULT 1,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


-- ----------------------------
-- Records of sand_tool_crontab_log
-- ----------------------------

-- ----------------------------
-- Table structure for sand_tool_generate_columns
-- ----------------------------
DROP TABLE IF EXISTS "sand_tool_generate_columns" CASCADE;
CREATE TABLE "sand_tool_generate_columns" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "table_id" integer NULL DEFAULT NULL,
  "column_name" varchar(200) NULL DEFAULT NULL,
  "column_comment" varchar(255) NULL DEFAULT NULL,
  "column_type" varchar(50) NULL DEFAULT NULL,
  "default_value" varchar(50) NULL DEFAULT NULL,
  "is_pk" smallint NULL DEFAULT 1,
  "is_required" smallint NULL DEFAULT 1,
  "is_insert" smallint NULL DEFAULT 1,
  "is_edit" smallint NULL DEFAULT 1,
  "is_list" smallint NULL DEFAULT 1,
  "is_query" smallint NULL DEFAULT 1,
  "is_sort" smallint NULL DEFAULT 1,
  "query_type" varchar(100) NULL DEFAULT 'eq',
  "view_type" varchar(100) NULL DEFAULT 'text',
  "dict_type" varchar(200) NULL DEFAULT NULL,
  "allow_roles" varchar(255) NULL DEFAULT NULL,
  "options" varchar(1000) NULL DEFAULT NULL,
  "sort" smallint NULL DEFAULT 0,
  "remark" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


-- ----------------------------
-- Records of sand_tool_generate_columns
-- ----------------------------

-- ----------------------------
-- Table structure for sand_tool_generate_tables
-- ----------------------------
DROP TABLE IF EXISTS "sand_tool_generate_tables" CASCADE;
CREATE TABLE "sand_tool_generate_tables" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "table_name" varchar(200) NULL DEFAULT NULL,
  "table_comment" varchar(500) NULL DEFAULT NULL,
  "stub" varchar(50) NULL DEFAULT NULL,
  "template" varchar(50) NULL DEFAULT NULL,
  "namespace" varchar(255) NULL DEFAULT NULL,
  "package_name" varchar(100) NULL DEFAULT NULL,
  "business_name" varchar(50) NULL DEFAULT NULL,
  "class_name" varchar(50) NULL DEFAULT NULL,
  "menu_name" varchar(100) NULL DEFAULT NULL,
  "belong_menu_id" integer NULL DEFAULT NULL,
  "tpl_category" varchar(100) NULL DEFAULT NULL,
  "generate_type" smallint NULL DEFAULT 1,
  "generate_path" varchar(100) NULL DEFAULT 'sandadmin-artd',
  "generate_model" smallint NULL DEFAULT 1,
  "generate_menus" varchar(255) NULL DEFAULT NULL,
  "build_menu" smallint NULL DEFAULT 1,
  "component_type" smallint NULL DEFAULT 1,
  "options" varchar(1500) NULL DEFAULT NULL,
  "form_width" integer NULL DEFAULT 800,
  "is_full" smallint NULL DEFAULT 1,
  "remark" varchar(255) NULL DEFAULT NULL,
  "source" varchar(255) NULL DEFAULT NULL,
  "created_by" integer NULL DEFAULT NULL,
  "updated_by" integer NULL DEFAULT NULL,
  "create_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "update_time" timestamp(0) without time zone NULL DEFAULT NULL,
  "delete_time" timestamp(0) without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


-- ----------------------------
-- Records of sand_tool_generate_tables
-- ----------------------------

-- Keep identity sequences in sync with the explicit bootstrap IDs.
SELECT setval(pg_get_serial_sequence('public.sand_system_attachment', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_attachment"), 1), EXISTS (SELECT 1 FROM "sand_system_attachment"));
SELECT setval(pg_get_serial_sequence('public.sand_system_category', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_category"), 1), EXISTS (SELECT 1 FROM "sand_system_category"));
SELECT setval(pg_get_serial_sequence('public.sand_system_config', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_config"), 1), EXISTS (SELECT 1 FROM "sand_system_config"));
SELECT setval(pg_get_serial_sequence('public.sand_system_config_group', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_config_group"), 1), EXISTS (SELECT 1 FROM "sand_system_config_group"));
SELECT setval(pg_get_serial_sequence('public.sand_system_dept', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_dept"), 1), EXISTS (SELECT 1 FROM "sand_system_dept"));
SELECT setval(pg_get_serial_sequence('public.sand_system_dict_data', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_dict_data"), 1), EXISTS (SELECT 1 FROM "sand_system_dict_data"));
SELECT setval(pg_get_serial_sequence('public.sand_system_dict_type', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_dict_type"), 1), EXISTS (SELECT 1 FROM "sand_system_dict_type"));
SELECT setval(pg_get_serial_sequence('public.sand_system_login_log', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_login_log"), 1), EXISTS (SELECT 1 FROM "sand_system_login_log"));
SELECT setval(pg_get_serial_sequence('public.sand_system_mail', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_mail"), 1), EXISTS (SELECT 1 FROM "sand_system_mail"));
SELECT setval(pg_get_serial_sequence('public.sand_system_menu', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_menu"), 1), EXISTS (SELECT 1 FROM "sand_system_menu"));
SELECT setval(pg_get_serial_sequence('public.sand_system_oper_log', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_oper_log"), 1), EXISTS (SELECT 1 FROM "sand_system_oper_log"));
SELECT setval(pg_get_serial_sequence('public.sand_system_post', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_post"), 1), EXISTS (SELECT 1 FROM "sand_system_post"));
SELECT setval(pg_get_serial_sequence('public.sand_system_role', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_role"), 1), EXISTS (SELECT 1 FROM "sand_system_role"));
SELECT setval(pg_get_serial_sequence('public.sand_system_role_dept', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_role_dept"), 1), EXISTS (SELECT 1 FROM "sand_system_role_dept"));
SELECT setval(pg_get_serial_sequence('public.sand_system_role_menu', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_role_menu"), 1), EXISTS (SELECT 1 FROM "sand_system_role_menu"));
SELECT setval(pg_get_serial_sequence('public.sand_system_user', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_user"), 1), EXISTS (SELECT 1 FROM "sand_system_user"));
SELECT setval(pg_get_serial_sequence('public.sand_system_user_post', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_user_post"), 1), EXISTS (SELECT 1 FROM "sand_system_user_post"));
SELECT setval(pg_get_serial_sequence('public.sand_system_user_role', 'id'), COALESCE((SELECT MAX("id") FROM "sand_system_user_role"), 1), EXISTS (SELECT 1 FROM "sand_system_user_role"));
SELECT setval(pg_get_serial_sequence('public.sand_tool_crontab', 'id'), COALESCE((SELECT MAX("id") FROM "sand_tool_crontab"), 1), EXISTS (SELECT 1 FROM "sand_tool_crontab"));
SELECT setval(pg_get_serial_sequence('public.sand_tool_crontab_log', 'id'), COALESCE((SELECT MAX("id") FROM "sand_tool_crontab_log"), 1), EXISTS (SELECT 1 FROM "sand_tool_crontab_log"));
SELECT setval(pg_get_serial_sequence('public.sand_tool_generate_columns', 'id'), COALESCE((SELECT MAX("id") FROM "sand_tool_generate_columns"), 1), EXISTS (SELECT 1 FROM "sand_tool_generate_columns"));
SELECT setval(pg_get_serial_sequence('public.sand_tool_generate_tables', 'id'), COALESCE((SELECT MAX("id") FROM "sand_tool_generate_tables"), 1), EXISTS (SELECT 1 FROM "sand_tool_generate_tables"));
