<?php

declare(strict_types=1);

/**
 * Generates this package's PostgreSQL install.sql from the bundled upstream
 * MySQL schema.  The generated file is consumed by SaiPackage, which always
 * looks for a file named install.sql.
 *
 * Usage: php tools/convert-install-sql.php /path/to/upstream/install.sql
 */

final class SandWorkflowPostgresSqlConverter
{
    /** @var list<string> */
    private array $identityTables = [];

    /** @var array<string, string> */
    private const MENU_CODES = [
        'sw_root' => 'SandWorkflow',
        'sw_center' => 'SandWorkflowCenter',
        'sw_start' => 'sandworkflow/center/start',
        'sw_task' => 'sandworkflow/center/task',
        'sw_my' => 'sandworkflow/center/my',
        'sw_processed' => 'sandworkflow/center/processed',
        'sw_copy' => 'sandworkflow/center/copy',
        'sw_manage' => 'SandWorkflowManage',
        'sw_group' => 'sandworkflow/manage/group',
        'sw_definition' => 'sandworkflow/manage/definition',
        'sw_data' => 'sandworkflow/data/instance',
        'sw_org' => 'sandworkflow/org',
    ];

    public function convert(string $source): string
    {
        $sql = file_get_contents($source);
        if ($sql === false) {
            throw new RuntimeException("Unable to read {$source}");
        }

        $this->identityTables = [];
        $sql = preg_replace('/^SET\s+NAMES.*?;\s*$/mi', '', $sql) ?? $sql;
        $sql = preg_replace_callback(
            '/DROP TABLE IF EXISTS `([^`]+)`;/i',
            static fn (array $matches): string => sprintf('DROP TABLE IF EXISTS "%s";', $matches[1]),
            $sql,
        ) ?? $sql;
        $sql = preg_replace_callback(
            '/CREATE TABLE `([^`]+)`\s*\((.*?)\)\s*ENGINE\s*=?.*?;/si',
            fn (array $matches): string => $this->convertTable($matches[1], $matches[2]),
            $sql,
        ) ?? $sql;
        $sql = preg_replace('/INSERT INTO `([^`]+)`/i', 'INSERT INTO "$1"', $sql) ?? $sql;
        $sql = str_replace('`', '"', $sql);
        $sql = preg_replace('/^SET @sw_[a-z_]+ := LAST_INSERT_ID\(\);\s*$/mi', '', $sql) ?? $sql;

        foreach (self::MENU_CODES as $variable => $code) {
            $replacement = sprintf("(SELECT \"id\" FROM \"sa_system_menu\" WHERE \"code\" = '%s')", $code);
            $sql = str_replace('@' . $variable, $replacement, $sql);
        }

        return trim($sql) . "\n\n" . $this->sequenceStatements() . "\n";
    }

    private function convertTable(string $table, string $body): string
    {
        $definitions = [];
        $indexes = [];
        foreach (preg_split('/\R/u', trim($body)) ?: [] as $line) {
            $line = trim($line);
            if ($line === '') {
                continue;
            }
            $line = rtrim($line, ',');
            if (str_starts_with($line, 'PRIMARY KEY')) {
                $definitions[] = str_replace('`', '"', $line);
                continue;
            }
            if (preg_match('/^(?:UNIQUE\s+)?KEY\s+`/i', $line) === 1) {
                $indexes[] = $this->convertIndex($table, $line);
                continue;
            }
            $definitions[] = $this->convertColumn($table, $line);
        }

        return sprintf(
            "CREATE TABLE \"%s\" (\n  %s\n);\n%s",
            $table,
            implode(",\n  ", $definitions),
            implode("\n", $indexes),
        );
    }

    private function convertColumn(string $table, string $definition): string
    {
        if (!preg_match('/^`([^`]+)`\s+(.+)$/', $definition, $matches)) {
            throw new RuntimeException("Unsupported column definition in {$table}: {$definition}");
        }
        $column = $matches[1];
        $definition = $matches[2];
        $isIdentity = stripos($definition, 'AUTO_INCREMENT') !== false;
        $definition = preg_replace('/\s+COMMENT\s+\'(?:[^\'\\\\]|\\\\.)*\'/u', '', $definition) ?? $definition;
        $definition = preg_replace('/\s+UNSIGNED\b/i', '', $definition) ?? $definition;
        $definition = preg_replace('/\s+CHARACTER\s+SET\s+\w+/i', '', $definition) ?? $definition;
        $definition = preg_replace('/\s+COLLATE\s+\w+/i', '', $definition) ?? $definition;
        $definition = preg_replace('/\bAUTO_INCREMENT\b/i', 'GENERATED BY DEFAULT AS IDENTITY', $definition) ?? $definition;
        $definition = preg_replace('/\bBIGINT\(\d+\)/i', 'bigint', $definition) ?? $definition;
        $definition = preg_replace('/\bINT\(\d+\)/i', 'integer', $definition) ?? $definition;
        $definition = preg_replace('/\bTINYINT(?:\(\d+\))?/i', 'smallint', $definition) ?? $definition;
        $definition = preg_replace('/\bDATETIME(?:\(\d+\))?/i', 'timestamp(0) without time zone', $definition) ?? $definition;
        $definition = preg_replace('/\bJSON\b/i', 'jsonb', $definition) ?? $definition;

        if ($isIdentity && $column === 'id') {
            $this->identityTables[] = $table;
        }

        return sprintf('"%s" %s', $column, trim($definition));
    }

    private function convertIndex(string $table, string $definition): string
    {
        if (!preg_match('/^(UNIQUE\s+)?KEY\s+`([^`]+)`\s*\((.+)\)$/i', $definition, $matches)) {
            throw new RuntimeException("Unsupported index definition in {$table}: {$definition}");
        }
        $unique = $matches[1] !== '' ? 'UNIQUE ' : '';
        $columns = preg_replace('/`([^`]+)`/', '"$1"', $matches[3]) ?? $matches[3];
        return sprintf('CREATE %sINDEX "idx_%s_%s" ON "%s" (%s);', $unique, $table, $matches[2], $table, $columns);
    }

    private function sequenceStatements(): string
    {
        $statements = ['-- Keep identities in sync with explicit bootstrap IDs.'];
        foreach (array_values(array_unique($this->identityTables)) as $table) {
            $statements[] = sprintf(
                "SELECT setval(pg_get_serial_sequence('public.%s', 'id'), COALESCE((SELECT MAX(\"id\") FROM \"%s\"), 1), EXISTS (SELECT 1 FROM \"%s\"));",
                $table,
                $table,
                $table,
            );
        }
        return implode("\n", $statements);
    }
}

$source = $argv[1] ?? '';
if ($source === '' || !is_file($source)) {
    fwrite(STDERR, "Usage: php tools/convert-install-sql.php /path/to/upstream/install.sql\n");
    exit(1);
}

$packageRoot = dirname(__DIR__);
$converter = new SandWorkflowPostgresSqlConverter();
$sql = $converter->convert($source);
foreach ([$packageRoot . '/install.sql', $packageRoot . '/plugin/sandworkflow/install.sql'] as $target) {
    file_put_contents($target, $sql);
    fwrite(STDOUT, "Generated {$target}\n");
}
